### PR TITLE
Add github action

### PR DESCRIPTION
**Pull request by amai2012**

### CODE REVIEW

**Comment by lowleveldesign** [comment]
Hi, great thanks for the PR. I was actually using Azure DevOps for building this app, but I'd gladly switch to GitHub Actions. There is one script I run before the build: https://github.com/lowleveldesign/wtrace/blob/master/scripts/Update-AssemblyInfoVersionFiles.ps1. Could you add this step to the pipeline too?

**Comment by amai2012** [comment]
That's not complex by itself, but as the failure on https://github.com/amai2012/wtrace/runs/589979419?check_suite_focus=true suggests we need to provide a cmdline argument I guess?

I commented out that call for now.
OTOH I added artifacts meanwhile...

**Comment by lowleveldesign** [comment]
Ah right, the powershell script requires a build variable (build number) to be set. I am busy with other stuff right now, but will check this over the weekend. Thanks again for contributing.

**Comment by lowleveldesign** [comment]
The script is now working. I found that Github Actions has the `GITHUB_RUN_NUMBER` variable I could use. Thanks!

**Pull request merged**
